### ISSUE TITLE
Hosts provisioner incomplete on early hosts in multi-vm situations

### ISSUE THREAD

**Issue by reidmv** [oscar-stack/vagrant-hosts#17]
As near as I can tell, at present when the provisioner runs, it will only install hosts entries for the machines currently running. That might be expandable to "machines currently created", but I haven't tested specifically. In any case, it's definitely true that for machines not yet created, no hosts entries will be added.

This means that if I have an environment defined with three machines, box1, box2, and box3, if I do a `vagrant up` then:

* box1 will have hosts entries for: [box1]
* box2 will have hosts entries for: [box1, box2]
* box3 will have hosts entries for: [box1, box2, box3]

The root of this behavior seems to be that the all_machines() method in the provisioner returns `@env.active_machines.map { |vm_id| @env.machine(*vm_id) }`. Well, at the time box1 spins up neither box2 nor box3 are active, and so won't show up in active_machines (or at least that's what seems to be the case based on VAGRANT_LOG=debug output).

Poking around, it looks like the thing to do would be to investigate whether or not there is a way of getting ALL machine configuration, not just active machines, out of the `@env` object somehow.

**Comment by rhubarb** [comment]
Why is this closed? Is it fixed?
I get why it's tricky and understand the workaround, but it's a major fail imo:
1. when would I really want to use this plugin in a NON multi-vm setup?
2. when would I want to use it in a multi-vm setup and NOT want all of my vms to know all of the others.

The whole point of vagrant is that I can start from nothing and get everything working with vagrant-up. I simply can't with this.

**Comment by mnarrell** [comment]
It's closed, I assume, because there is a viable workaround.  I ran into this exact issue and have side stepped it with:

```
alias vu='vagrant up --no-provision && vagrant provision'
```

**Comment by adrienthebo** [comment]
@rhubarb this issue isn't closed; you may be mistaking the fact that another issue referenced this issue, and that one was closed.

**Comment by Sharpie** [comment]
This is finally possible in 2.6.0 by setting the new `sync_hosts` option to `true`. I've opened issue #52 for making this the default behavior in 3.0.0.
