### ISSUE TITLE
Minor clarifications on readme

### ISSUE THREAD

**Issue by pydolan** [oscar-stack/vagrant-hosts#21]
1) When trying to auto-configure a box via `node.vm.provision :hosts`, the first box brought online does not seem to auto-configure. Instead, I had to explicitly turn on auto-configuring: 

    # my fix to get 1st box auto-configuring:
    node.vm.network :private_network, ip: "10.20.1.2"
    node.vm.provision :hosts do |h|
      h.autoconfigure = true
    end
 
    # only works for 2nd, 3rd, etc. boxes (i.e. /etc/hosts left unchanged on 1st box): 
    node.vm.network :private_network, ip: "10.20.1.2"
    node.vm.provision :hosts

2) add_host calls need quotes around IP address:

    # works:
    provisioner.add_host '172.16.3.10', ['yum.mirror.local']

    # doesn't work (error = "no .<digit> floating literal anymore; put 0 before dot")
    provisioner.add_host 172.16.3.10, ['yum.mirror.local']

**Comment by Sharpie** [comment]
Issue 1 seems like a case of #17, where autoconfigure only pulls hostnames from boxes that are already up and running.

Issue 2 was fixed in commit 95505239.
