### ISSUE TITLE
in vmware_fusion one can retrieve VM's eth0 ipaddresses

### ISSUE THREAD

**Issue by mrzarquon** [oscar-stack/vagrant-hosts#29]
In fusion, it stores the dhcp reservation table for all the guest vms in:

/var/db/vmware/

In theory it should be possible to have hosts populate /etc/hosts from there (we need to retrieve the eth0 mac address from vmware) to populate that information. This also removes the dependency on a secondary network interface and other crazy things since by default fusion guests can get NATed internet & talk to each other.

**Comment by Sharpie** [comment]
I'm going to mark this as resolved by v2.8.0 which added support for the `@facter_ipaddress` special key:

```ruby
config.vm.provision :hosts do |provisioner|
    provisioner.add_host '@facter_ipaddress', ['myhost.vagrantup.internal']
end
```

This string will be replaced by the IPv4 address of the interface serving as the default route. Despite the naming, Facter doesn't need to be installed --- this specific fact is emulated by the vagrant-hosts plugin. In the future we could extend this functionality to provide addresses for each interface.
