### ISSUE TITLE
Way to inspect vhosts of guest and add entries to hosts file on host OS?

### ISSUE THREAD

**Issue by BrianGilbert** [oscar-stack/vagrant-hosts#47]
Wondering if there is a way that this could be done?

considerations: apache and nginx..

**Comment by Sharpie** [comment]
There is a way to do this, the `vagrant hosts list` command will print out hostname info for all private_network interfaces:

```
$ vagrant hosts list

10.20.1.28 pe-201522-agent-win2012 pe-201522-agent-win2012
10.20.1.19 pe-201522-master.puppetdebug.vlan pe-201522-master
```

Updated the README with a mention of this command.
