### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by axl89** [oscar-stack/vagrant-hosts#55]
After installing the prerequisites, when I execute `vagrant up` after waiting about 5 minutes I get:

    Bringing machine 'dockerhost01' up with 'virtualbox' provider...
    Bringing machine 'dockerhost02' up with 'virtualbox' provider...
    Bringing machine 'dockerhost03' up with 'virtualbox' provider...
    Bringing machine 'dockerswarm01' up with 'virtualbox' provider...
    ==> dockerhost01: Importing base box 'vbox-trusty64-20150111.box'...
    ==> dockerhost01: Matching MAC address for NAT networking...
    ==> dockerhost01: Setting the name of the VM: docker-swarm-demo-master_dockerhost01_1457379620755_95182
    ==> dockerhost01: Clearing any previously set network interfaces...
    ==> dockerhost01: Preparing network interfaces based on configuration...
        dockerhost01: Adapter 1: nat
        dockerhost01: Adapter 2: hostonly
    ==> dockerhost01: Forwarding ports...
        dockerhost01: 22 (guest) => 2222 (host) (adapter 1)
    ==> dockerhost01: Running 'pre-boot' VM customizations...
    ==> dockerhost01: Booting VM...
    ==> dockerhost01: Waiting for machine to boot. This may take a few minutes...
        dockerhost01: SSH address: 127.0.0.1:2222
        dockerhost01: SSH username: vagrant
        dockerhost01: SSH auth method: private key
    Timed out while waiting for the machine to boot. This means that
    Vagrant was unable to communicate with the guest machine within
    the configured ("config.vm.boot_timeout" value) time period.

    If you look above, you should be able to see the error(s) that
    Vagrant had when attempting to connect to the machine. These errors
    are usually good hints as to what may be wrong.

    If you're using a custom box, make sure that networking is properly
    working and you're able to connect to the machine. It is a common
    problem that networking isn't setup properly in these boxes.
    Verify that authentication configurations are also setup properly,
    as well.

    If the box appears to be booting properly, you may want to increase
    the timeout ("config.vm.boot_timeout") value.

**Comment by axl89** [comment]
More data that may be useseful:

1. I am using CentOS 7 with kernel 3.10.0-327.10.1, **VirtualBox** as provider (I compiled the VBox driver successfully)

2. I am able to connect via SSH to 127.0.0.1:2222, but I have no credentials... I think this may be the root of the problem(?)

**Comment by Sharpie** [comment]
The `vagrant-hosts` plugin manages `/etc/hosts` content after the machine is booted using a provisioner. From the output you've given above, it appears this issue is occurring before Vagrant has a chance to run any provisioners.

Are you using the `hosts` provisioner? If so, does this issue still occur if the `hosts` provisioner is removed from the VM configuration?

**Comment by Sharpie** [comment]
I'm marking this as closed as this failure doesn't seem to be related to vagrant-hosts.
