### ISSUE TITLE
not removing 127.0.0.1 entry that maps to hostname

### ISSUE THREAD

**Issue by cdmaestas** [oscar-stack/vagrant-hosts#71]
Should it not remove the 127.0.0.1 VMHOSTNAME entry?
---
 cat /etc/hosts
127.0.0.1 localhost
127.0.1.1 VMHOSTNAME
192.168.198.21 VMHOSTNAME
---

**Comment by Sharpie** [comment]
That entry can be disabled by setting `add_localhost_hostnames` to `false`:

https://github.com/oscar-stack/vagrant-hosts#provisioner-settings

Marking as a duplicate of #46.
